server:
  port: 6969
  servlet:
    context-path: /moblie

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_moblie
    username: root
    password: kien2005
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ngminhkieen05@gmail.com
    password: edyh aikk sewo aquh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  signerKey: "LoaRYfq4D8V/v47ttaDyDsDe/FbizZ7rix3tLf48JsU="

app:
  mail:
    from: ngminhkieen05@gmail.com